spring.application.name=order-and-cart-management
spring.datasource.url=jdbc:postgresql://localhost:5432/cartandorderdb
spring.datasource.username=postgres
spring.datasource.password=samko.1209
spring.jpa.hibernate.ddl-auto=update
server.port = 8084
eureka.client.service-url.defaultZone: http://localhost:8761/eureka/