version: '3.8'
services:
  product-service:
    image: samshatan/product-service
    container_name: product-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/practiceProductdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: samko.1209
    depends_on:
      - product-db
    networks:
      - training-network
  
  product-db:
    image: postgres:16-alpine
    container_name: product-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: samko.1209
      POSTGRES_DB: practiceProductdb
    ports:
      - "5440:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data
    networks:
      - training-network

  user-authentication-service:
    image: samshatan/user-authentication-service
    container_name: user-authentication-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-authentication-db:5432/practiceUserAuthdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: samko.1209
    depends_on:
      - user-authentication-db
    networks:
      - training-network

  user-authentication-db:
    image: postgres:16-alpine
    container_name: user-authentication-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: samko.1209
      POSTGRES_DB: practiceUserAuthdb
    ports:
      - "5441:5432"
    volumes:
      - user-authentication-db-data:/var/lib/postgresql/data
    networks:
      - training-network

volumes:
  product-db-data:
  user-authentication-db-data:

networks:
  training-network:
    driver: bridge