spring:
  datasource: 
    url: jdbc:postgresql://localhost:5432/practiceUserAuthdb
    username: postgres
    password: samko.1209
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true