spring:
  datasource: 
    url: jdbc:postgresql://localhost:5432/practiceUserAuthdb
    username: postgres
    password: samko.1209
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
     
application:
  security:
    jwt:
      secret-key: CWCGeY1l1ne/DVS6Xt9iycNI9LMmuFz9akesBJbQCmoKrtauWrMz4CfoDzn50zCtCAS0deEKzIpHReNB7pf88A==
      expiration: 604800000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/