spring.application.name=ProductService
spring.datasource.url=jdbc:postgresql://localhost:5432/practiceProductdb
spring.datasource.username=postgres
spring.datasource.password=samko.1209
server.port=8082
spring.jpa.hibernate.ddl-auto=update
eureka.client.service-url.defaultZone: http://localhost:8761/eureka/