spring.application.name=Training
spring.datasource.url=jdbc:postgresql://localhost:5432/practiceProductdb
spring.datasource.username=postgres
spring.datasource.password=samko.1209
server.port=8082
spring.jpa.hibernate.ddl-auto=update